databases:
  - name: werkaut
    databaseName: werkaut
    user: werkaut

services:
  - type: web
    name: werkaut
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn wger.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: werkaut
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
